import { TopBar } from "@/components/hq/TopBar";
import { Button } from "@/components/hq/Button";
import { Avatar } from "@/components/hq/Avatar";
import { LongDate } from "@/components/hq/LongDate";
import { briefingSections } from "@/lib/hq/mock-data";

export default function BriefingPage() {
  return (
    <div>
      <TopBar
        title="Daily Briefing"
        subtitle={<LongDate suffix=" · Generated by CEO AI at 06:00" />}
        actions={
          <>
            <Button variant="secondary" size="sm">
              Export PDF
            </Button>
            <Button variant="accent" size="sm">
              Ask a follow-up
            </Button>
          </>
        }
      />
      <div style={{ padding: "24px 32px", maxWidth: 760 }}>
        <div
          style={{
            background: "var(--accent-muted)",
            border: "1px solid var(--border-accent)",
            borderRadius: 8,
            padding: "14px 16px",
            display: "flex",
            alignItems: "center",
            gap: 10,
            marginBottom: 24,
          }}
        >
          <Avatar name="CEO AI" isAI size="sm" />
          <span style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 }}>
            This briefing synthesises data from{" "}
            <strong style={{ color: "var(--text-primary)" }}>12 connected integrations</strong> and{" "}
            <strong style={{ color: "var(--text-primary)" }}>7 AI agents</strong>. Every recommendation includes its source.
          </span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
          {briefingSections.map((s, i) => (
            <div key={i}>
              <div
                style={{
                  fontSize: 11,
                  fontWeight: 600,
                  letterSpacing: "0.08em",
                  textTransform: "uppercase",
                  color: "var(--text-accent)",
                  marginBottom: 10,
                }}
              >
                {String(i + 1).padStart(2, "0")} / {s.title}
              </div>
              <p
                style={{
                  fontSize: 14,
                  color: "var(--text-secondary)",
                  lineHeight: 1.7,
                  whiteSpace: "pre-line",
                  letterSpacing: "-0.005em",
                }}
              >
                {s.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
