import { TopBar } from "@/components/hq/TopBar";
import { Card } from "@/components/hq/Card";
import { Badge } from "@/components/hq/Badge";
import { Button } from "@/components/hq/Button";
import { Avatar } from "@/components/hq/Avatar";
import { LongDate } from "@/components/hq/LongDate";
import { MetricCard } from "@/components/hq/MetricCard";
import { AttentionRow } from "@/components/hq/AttentionRow";
import { ActivityRow } from "@/components/hq/ActivityRow";
import { metrics, attentionItems, activityItems, briefingHighlights } from "@/lib/hq/mock-data";

export default function ExecutivePage() {
  return (
    <div>
      <TopBar
        title="Good morning."
        subtitle={<LongDate suffix=" · Here's what matters today." />}
        actions={
          <>
            <Button variant="secondary" size="sm">
              Export briefing
            </Button>
            <Button variant="accent" size="sm">
              Ask AI
            </Button>
          </>
        }
      />

      <div style={{ padding: "24px 32px", display: "flex", flexDirection: "column", gap: 20 }}>
        <Card accent padding="md">
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginBottom: 14 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <Avatar name="CEO AI" isAI size="sm" />
              <div>
                <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-accent)", letterSpacing: "-0.01em" }}>
                  Today&apos;s Executive Briefing
                </div>
                <div style={{ fontSize: 11, color: "var(--text-tertiary)" }}>Generated by CEO AI · 06:00 this morning</div>
              </div>
            </div>
            <Button variant="ghost" size="sm" href="/hq/briefing">
              Read full →
            </Button>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {briefingHighlights.map((line, i) => (
              <div key={i} style={{ display: "flex", gap: 10 }}>
                <span style={{ color: "var(--text-accent)", flexShrink: 0 }}>—</span>
                <span style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.55 }}>{line}</span>
              </div>
            ))}
          </div>
        </Card>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
          {metrics.map((m, i) => (
            <MetricCard key={i} {...m} />
          ))}
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
          <Card padding="md">
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)", letterSpacing: "-0.01em" }}>
                Needs attention
              </span>
              <Badge variant="error" size="sm">
                {attentionItems.length}
              </Badge>
            </div>
            {attentionItems.map((a, i) => (
              <AttentionRow key={i} {...a} />
            ))}
          </Card>

          <Card padding="md">
            <div style={{ marginBottom: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)", letterSpacing: "-0.01em" }}>
                What changed overnight
              </span>
            </div>
            {activityItems.map((a, i) => (
              <ActivityRow key={i} {...a} />
            ))}
          </Card>
        </div>
      </div>
    </div>
  );
}
