/** @typedef {import('./ops-shared').OpsData} OpsData */

/** @type {OpsData} */
export const DEFAULT_OPS = {
  updatedAt: null,
  todayPriorities: [
    { id: "tp-1", title: "Pick one P0 on Sookly action plan and finish it", done: false, stream: "sookly-website" },
    { id: "tp-2", title: "Clear blockers + set tomorrow’s 3 priorities", done: false, stream: "ops" },
    { id: "tp-3", title: "Log one decision or briefing note", done: false, stream: "ops" },
  ],
  workstreams: {
    sooklyWebsite: {
      label: "sookly.co",
      product: "sookly",
      boardHref: "/hq/sookly/action-plan",
      items: [
        { id: "sw-1", title: "Pricing page — align with KB and early-access offer", status: "doing", priority: "P0", owner: "James", due: "2026-08-03", links: [{ label: "sookly.co", url: "https://sookly.co" }] },
        { id: "sw-2", title: "Early-access landing page conversion pass", status: "todo", priority: "P0", owner: "James", due: "2026-08-05", links: [] },
        { id: "sw-3", title: "FAQ page wired to canonical KB exports", status: "todo", priority: "P1", owner: "James", due: "2026-07-31", links: [] },
        { id: "sw-4", title: "Blog / resources hub structure", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [] },
        { id: "sw-5", title: "Schema.org + llms.txt from SEOS exports on site", status: "todo", priority: "P2", owner: "James", due: "2026-08-01", links: [] },
      ],
    },
    sooklyApp: {
      label: "app.sookly.com",
      product: "sookly",
      boardHref: "/hq/sookly/action-plan",
      items: [
        { id: "sa-1", title: "Auth + workspace shell for app subdomain", status: "doing", priority: "P0", owner: "James", due: "2026-07-30", links: [{ label: "app target", url: "https://app.sookly.com" }] },
        { id: "sa-2", title: "Receptionist inbox MVP — unified channel list", status: "todo", priority: "P0", owner: "James", due: "2026-08-03", links: [] },
        { id: "sa-3", title: "KB consumption layer (read-only from SEOS)", status: "todo", priority: "P0", owner: "James", due: "2026-08-05", links: [{ label: "HQ readiness view", url: "/hq/sookly/receptionist-readiness" }] },
        { id: "sa-4", title: "Settings: business hours + handoff rules", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [] },
        { id: "sa-5", title: "Deploy preview environment + smoke tests", status: "todo", priority: "P1", owner: "James", due: "2026-08-08", links: [] },
      ],
    },
    seosSocial: {
      label: "SEOS Social GTM",
      product: "seos",
      boardHref: "/hq/seos/social-gtm",
      items: [
        { id: "ss-1", title: "Document Content Engine → Publishing Queue handoff (one article → assets)", status: "doing", priority: "P0", owner: "James", due: "2026-08-01", links: [{ label: "SEOS Hub", url: "/hq/seos" }], pillar: null },
        { id: "ss-2", title: "Platform matrix UX: honest Manual / Draft / Future OAuth badges only", status: "todo", priority: "P0", owner: "James", due: "2026-08-02", links: [] },
        { id: "ss-3", title: "Facebook Page adapter stub (no live Graph API yet)", status: "todo", priority: "P0", owner: "James", due: "2026-07-30", links: [], platform: "facebook_page" },
        { id: "ss-4", title: "Instagram draft-media publish path design", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [], platform: "instagram" },
        { id: "ss-5", title: "TikTok manual upload checklist in queue UI", status: "todo", priority: "P1", owner: "James", due: "2026-08-08", links: [], platform: "tiktok" },
        { id: "ss-6", title: "Reddit + LinkedIn + X adapter stubs (Future OAuth)", status: "todo", priority: "P1", owner: "James", due: "2026-08-12", links: [] },
        { id: "ss-7", title: "Threads (#7) manual schedule notes + tone enforcement from KB", status: "todo", priority: "P2", owner: "James", due: "2026-08-15", links: [], platform: "threads" },
        { id: "ss-8", title: "OAuth credential store design (Phase 3) — no keys in repo", status: "todo", priority: "P2", owner: "James", due: "2026-08-20", links: [] },
      ],
    },
    roastMyOpSec: {
      label: "RoastMyOpSec",
      product: "roastmyopsec",
      boardHref: "/hq/roastmyopsec",
      items: [
        { id: "rm-1", title: "Define surface inventory fields (domains, public channels, KB map)", status: "doing", priority: "P0", owner: "James", due: "2026-08-03", links: [{ label: "Open SEOS", url: "https://seos.sooklabs.com" }] },
        { id: "rm-2", title: "Plain-English exposure report outline (founder-facing)", status: "todo", priority: "P0", owner: "James", due: "2026-08-01", links: [] },
        { id: "rm-3", title: "Read-only consume SEOS website content map + contact channels", status: "todo", priority: "P1", owner: "James", due: "2026-08-08", links: [{ label: "Open SEOS", url: "https://seos.sooklabs.com" }] },
        { id: "rm-4", title: "Roast UX wireframe — never edits business truth", status: "todo", priority: "P1", owner: "James", due: "2026-08-12", links: [] },
        { id: "rm-5", title: "Scanner engine / live checks (Future API)", status: "todo", priority: "P2", owner: "James", due: "2026-09-01", links: [] },
      ],
    },
    community: {
      label: "Community (Discord)",
      product: "community",
      boardHref: "/hq/community",
      items: [
        { id: "cm-1", title: "Discord server structure: roles, channels, three pillars", status: "doing", priority: "P0", owner: "James", due: "2026-08-05", links: [], pillar: "structure" },
        { id: "cm-2", title: "Psychology pillar — starter topics + cadence", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [], pillar: "psychology" },
        { id: "cm-3", title: "Investment pillar — starter topics + cadence", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [], pillar: "investment" },
        { id: "cm-4", title: "Technology pillar — starter topics + cadence", status: "todo", priority: "P1", owner: "James", due: "2026-08-05", links: [], pillar: "technology" },
        { id: "cm-5", title: "Subscription / gating design (Future API — no Stripe yet)", status: "todo", priority: "P2", owner: "James", due: "2026-08-25", links: [], pillar: "structure" },
        { id: "cm-6", title: "Hosting ops: ownership, moderators, onboarding doc", status: "todo", priority: "P1", owner: "James", due: "2026-08-15", links: [], pillar: "structure" },
      ],
    },
    personal: {
      label: "Personal ops",
      product: "personal",
      boardHref: "/hq/goals",
      items: [
        {
          id: "pe-1",
          title: "Weekly review: goals + blockers + decisions (thin personal loop)",
          status: "todo",
          priority: "P1",
          owner: "Mark",
          due: null,
          links: [{ label: "Goals", url: "/hq/goals" }],
        },
      ],
    },
  },
  mvpMilestones: [
    { id: "sookly", name: "Sookly", stage: "mvp1", href: "/hq/sookly/action-plan", workstreamKeys: ["sooklyWebsite", "sooklyApp"] },
    { id: "seos", name: "SEOS", stage: "prototype", href: "/hq/seos/social-gtm", workstreamKeys: ["seosSocial"] },
    { id: "roastmyopsec", name: "RoastMyOpSec", stage: "discover", href: "/hq/roastmyopsec", workstreamKeys: ["roastMyOpSec"] },
    { id: "community", name: "Community", stage: "discover", href: "/hq/community", workstreamKeys: ["community"] },
    { id: "personal", name: "Personal", stage: "thin", href: "/hq/goals", workstreamKeys: ["personal"] },
  ],
  platformMatrix: [
    { id: "facebook_page", label: "Facebook Page", mode: "future_oauth", note: "Meta Graph — not connected" },
    { id: "instagram", label: "Instagram", mode: "future_oauth", note: "Draft media path first" },
    { id: "tiktok", label: "TikTok", mode: "manual", note: "Manual upload until OAuth" },
    { id: "reddit", label: "Reddit", mode: "manual", note: "First-class platform TBD" },
    { id: "linkedin", label: "LinkedIn", mode: "draft", note: "Draft-only until OAuth" },
    { id: "x", label: "X (Twitter)", mode: "draft", note: "Draft-only until OAuth" },
    { id: "threads", label: "Threads", mode: "manual", note: "Platform #7 — Manual" },
  ],
  briefingNotes: {
    date: new Date().toISOString().slice(0, 10),
    sections: { priorities: "", risks: "", decisions: "" },
  },
  decisions: [
    { id: "d-1", date: "2026-07-03", title: "SEOS owns canonical Knowledge Base", body: "Sookly consumes via read-only views. No duplicate FAQ stores.", tags: ["architecture", "seos"] },
    { id: "d-2", date: "2026-07-01", title: "Phase 2 static KB implementation", body: "Mock KB + generators. No database until Phase 3.", tags: ["seos", "phase-2"] },
    { id: "d-3", date: "2026-06-28", title: "HQ subdomain password gate", body: "hq.sooklabs.com Phase 1 access control via shared password session.", tags: ["hq"] },
    { id: "d-4", date: "2026-07-08", title: "HQ is founder command center", body: "Daily ops live in HQ workstreams. SEOS social OAuth, Discord hosting, and RoastMyOpSec scanner are Future API — checklist boards only until approved.", tags: ["hq", "ops"] },
  ],
  agentJobs: [],
  morningLoop: { date: "", stepsChecked: [] },
  primaryBoardHref: "/hq/sookly/action-plan",
  goals: [
    {
      id: "g-1",
      title: "Ship HQ as a usable daily founder command centre",
      horizon: "2026-Q3",
      status: "active",
      product: "hq",
      notes: "Priorities, goals, blockers, decisions, briefing — not a SEOS SaaS shell.",
    },
    {
      id: "g-2",
      title: "SEOS Simple Mode: Context + Refactor + Authority for one workspace",
      horizon: "2026-Q3",
      status: "active",
      product: "seos",
      notes: "Outgoing control desk. Authority is one module.",
    },
    {
      id: "g-3",
      title: "Sookly MVP1 checklist progress without fake Live metrics",
      horizon: "2026-Q3",
      status: "active",
      product: "sookly",
      notes: "Track build in HQ; product execution at sookly.co.",
    },
  ],
  blockers: [],
};
